apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: maxf72ohk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maxf72ohk-go 
  name: maxf72ohk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: maxf72ohk-go 
